steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/hale-lims/hale-lims:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/hale-lims/hale-lims:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hale-lims'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/hale-lims/hale-lims:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=halelab-469206:asia-south1:hale-stg'
images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/hale-lims/hale-lims:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
