server.port=${PORT:8080}
spring.application.name=lims
spring.datasource.url=jdbc:postgresql:///<DB_NAME>?cloudSqlInstance=<INSTANCE_CONNECTION_NAME>&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.cloud.gcp.sql.instance-connection-name=<INSTANCE_CONNECTION_NAME>
spring.cloud.gcp.sql.database-name=postgres

# Hibernate DDL auto (for development, set to update; for production, set to none and manage migrations)
# change to 'none' for production and use Flyway/Liquibase
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Google Cloud Project ID
gcp.project.id=your-gcp-project-id

# Secret Manager secret name for the encryption key
# This secret should contain a Base64 encoded 32-byte (256-bit) AES key
encryption.secret-manager.key-name=lims-aes-256-key
gcs.default.bucket.name=your-lims-storage-bucket

jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkeymysecretkey
jwt.expiration=86400