server.port=8080
spring.application.name=lims

# PostgreSQL configuration for local development
# Replace your_database_name, your_username, and your_password with your local database credentials
spring.cloud.gcp.sql.enabled=true
spring.cloud.gcp.sql.instance-connection-name=jdbc:postgresql:///postgres?cloudSqlInstance=halelab-469206:asia-south1:hale-stg&socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryIpTypes=PUBLIC
spring.cloud.gcp.sql.database-name=postgres
spring.datasource.username=postgres
# spring.datasource.password=${sm://projects/halelab-469206/secrets/lims-db-password}
spring.datasource.password=,2$P#1B*7tbA@)?n
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate DDL auto (validate will validate the schema, use 'update' or 'create-drop' for development)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Disable Google Cloud SQL for local profile
#spring.cloud.gcp.sql.enabled=false
#spring.cloud.gcp.core.enabled=false

spring.cloud.gcp.secretmanager.enabled=false

# Google Cloud Project ID
gcp.project.id=halelab-469206

# Use a simple in-memory secret for local development
jwt.secret=local-secret-key-local-secret-key-local-secret-key
jwt.expiration=86400