server.port=${PORT:8080}
spring.application.name=lims
spring.datasource.url=jdbc:postgresql:///postgres?cloudSqlInstance=halelab-469206:asia-south1:hale-stg&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.cloud.gcp.sql.instance-connection-name=halelab-469206:asia-south1:hale-stg
spring.cloud.gcp.sql.database-name=postgres

# Hibernate DDL auto (for development, set to update; for production, set to none and manage migrations)
# change to 'none' for production and use Flyway/Liquibase
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Google Cloud Project ID
gcp.project.id=halelab-469206

# Secret Manager secret name for the encryption key
# This secret should contain a Base64 encoded 32-byte (256-bit) AES key
encryption.secret-manager.key-name=lims-aes-256-key
gcs.default.bucket.name=halelab-assets

jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkeymysecretkey
jwt.expiration=86400